# COMSOL batch with ASCII user.home (custom ini)
batch
-startup
D:\Program Files\COMSOL\COMSOL60\Multiphysics\plugins\org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar
--launcher.library
D:\Program Files\COMSOL\COMSOL60\Multiphysics\bin\win64
-install
D:\Program Files\COMSOL\COMSOL60\Multiphysics
-vm
D:\Program Files\COMSOL\COMSOL60\Multiphysics\java\win64\jre\bin\server\jvm.dll
-vmargs
-Duser.home=D:/comsol_q4/home
-Djava.io.tmpdir=D:/comsol_q4/tmp
-Dosgi.clean=true
-Dorg.osgi.service.log.admin.loglevel=ERROR
-Dosgi.locking=none
-Dosgi.configuration.cascaded=true
-Dosgi.sharedConfiguration.area=file:D:/Program Files/COMSOL/COMSOL60/Multiphysics/configuration/comsol
-Dosgi.sharedConfiguration.area.readOnly=true
-Dosgi.configuration.area=D:/comsol_q4/home/.comsol/v60/configuration/comsol_@process.id
-Dosgi.instance.area=D:/comsol_q4/home/.comsol/v60/workspace/comsol_@process.id
-Dosgi.checkConfiguration=true
-Declipse.security=
-Dcs.logoutput=file
-Dcs.logfileprefix=batch
-Dcs.uniqueworkspace=on
-Xss4m
-Xms40m
-Xmx4g
-XX:MaxMetaspaceSize=1g
-Dlog4j2.formatMsgNoLookups=true
